[versions]
kotlinVersion = "1.9.20"
gsonVersion = "2.10.1"
okioVersion = "3.8.0"
okhttpVersion = "4.12.0"

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }

[libraries]
gson = {module = "com.google.code.gson:gson", version.ref = "gsonVersion"}
okio = {module = "com.squareup.okio:okio", version.ref = "okioVersion"}
okhttp = {module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion"}
okhttpLoggingInterceptor = {module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttpVersion"}